### ISSUE TITLE
Use as OpenAI’s API

### ISSUE THREAD

**Issue by mmwong1984** [VadimBoev/freegpt-webui-v2#14]
Hello, I love this project. However, I use api more often than the webpage. However, in gpt4free’s project, it do not support the api in openai format.
So I think that make in this project is a good thing.
For example
The web chat page is http://domain.com
and the api is http://domain.com/api/v1/chat/completions

**Comment by VadimBoev** [comment]
hi, yes I understand, but I have no plans yet to make an accessible api as it is done in g4f
