### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by says112** [VadimBoev/freegpt-webui-v2#15]
![Снимок экрана (421)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/67f4a5dd-a638-4fd9-bcbd-198575e2164e)

**Comment by says112** [comment]
> Привет. Он не может найти зависимости. Прошу прощения за длинный ответ. Это актуально?

![Снимок экрана (536)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/8c8b63ba-a494-4105-9ebb-f370bc29c47b)

**Comment by VadimBoev** [comment]
you do not need to install g4f, because everything is available inside this repository, read the 'readme' to run

**Comment by says112** [comment]
> you do not need to install g4f, because everything is available inside this repository, read the 'readme' to run

![Снимок экрана (537)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/e101ec0b-a143-452e-b1c0-566b12058db0)
I installed it as described here.

**Comment by VadimBoev** [comment]
Use python version 3.10 and higher!!!!!!!!!!

**Comment by says112** [comment]
> Use python version 3.10 and higher!!!!!!!!!!

Thanks! Earned it!

**Comment by says112** [comment]
![Uploading Снимок экрана (538).png…]()
GPT-4 bugs.

**Comment by says112** [comment]
![Снимок экрана (538)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/6cf5c43a-82e1-413b-8183-7745ea86dc46)

**Comment by VadimBoev** [comment]
"GPT-4 works, but with some providers.
It happens that when you automatically select a provider, GPT-4 may not work.
Choose one and find a working option."

**Comment by VadimBoev** [comment]
download the latest release

**Comment by says112** [comment]
![Снимок экрана (539)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/bb0e0a39-ee64-4aa5-8a0e-c24eda673785)
broke down

**Comment by VadimBoev** [comment]
pip install flask

**Comment by says112** [comment]
It is not installed. pip does not install anything at all.

**Comment by says112** [comment]
![Снимок экрана (540)](https://github.com/VadimBoev/freegpt-webui-v2/assets/22127398/28b2de13-3bd3-4d12-9495-f3ce5ae6077f)

**Comment by says112** [comment]
Заработал устанавливал через: python -m pip install ....
