### ISSUE TITLE
missing python modules in requirements.txt

### ISSUE THREAD

**Issue by nephaste** [VadimBoev/freegpt-webui-v2#17]
Hi 

just installed 0.3 version , seems some python modules are missing in the requirements-txt 

i add to add the following : in my venv

bin/pip install undetected-chromedriver ;
bin/pip install py-arkose-generator;
bin/pip install asyncstdlib;
bin/pip install async_property;

thanks again for this great work

**Comment by VadimBoev** [comment]
Hi. Thanks! 
I forgot that g4f has updated something and added new dependencies.
