### ISSUE TITLE
Error SSL in demo

### ISSUE THREAD

**Issue by Turbo1337GS** [VadimBoev/freegpt-webui-v2#18]
![Screenshot_2024-01-03-02-25-52-131_com.android.chrome.jpg](https://github.com/VadimBoev/freegpt-webui-v2/assets/137882010/addbfe61-d0f5-4f9e-b34a-f31f9da5a2fe)

**Comment by VadimBoev** [comment]
Hi. http://vadimboev.ru:1338 / would be more correct, and it works without SSL.

**Comment by Turbo1337GS** [comment]
> Hi. http://vadimboev.ru:1338 / would be more correct, and it works without SSL.

Thanks this work :)
