### ISSUE TITLE
No module named 'js2py' and error in UI

### ISSUE THREAD

**Issue by nephaste** [VadimBoev/freegpt-webui-v2#2]
Hi 

thanks for this version

unsing python 3.10 in virtualenv and seems

js2py missing in requirements.txt

![image](https://github.com/VadimBoev/freegpt-webui-v2/assets/3392684/684ca2a0-b6c9-446c-be0a-ab8fd7a31d27)

installed with pip3 fixed the missing module, ui start,

**Comment by VadimBoev** [comment]
Hi. Yes, it really is. I didn't see this in g4f when I tested the new version, but js2py was already installed in my system, or I installed it once, I don't remember anymore. Thanks, I'll update the 'requirements'
