### ISSUE TITLE
Chat titel length 

### ISSUE THREAD

**Issue by Mylinde** [VadimBoev/freegpt-webui-v2#22]
Doing some UI rework and want to change the length for the conversation.titel string. So far it looks like that it doesn't be shortened in the chat.js. Does the API shortening it?

**Comment by VadimBoev** [comment]
No, the API does not shorten the incoming line from the user. As it is, it all depends on the tokens for the incoming string from the API side

**Comment by Mylinde** [comment]
So, no way to change this?

**Comment by Mylinde** [comment]
conversation-titel lenght is set in chat.js `add_conversation(window.conversation_id, message.substr(0, 30));` set it to 30 and added css rule `.conversation-title {
    white-space: pre-wrap;
    overflow-y: clip;
    max-height: 18px;
}` an we have a clean end after a whole word..
