### ISSUE TITLE
highlightjs-copy Not working

### ISSUE THREAD

**Issue by Mylinde** [VadimBoev/freegpt-webui-v2#23]
Highlighting works, the copy button appears but by pressing the button the highlighted content won't be copied.

**Comment by VadimBoev** [comment]
That's right!

**Comment by Mylinde** [comment]
Highlighting layout is fixed, but copying still not working. Have you checked it? Is it working?

**Comment by Mylinde** [comment]
Update this issue. Highlightjs-copy only works with a secure origin. To work with an insecure origin, we need to enable chrome://flags/#unsafely-treat-insecure-origin-as-secure in Chromium-based browsers and set the origin. Other browsers may have a similar setting. This came about while looking for a solution for a working PWA without https.
... PWA comes with the next pull
