### ISSUE TITLE
issue in requirements.txt  

### ISSUE THREAD

**Issue by nephaste** [VadimBoev/freegpt-webui-v2#27]
trying to compile into a venv with Python 3.11

getting this error : bin/pip3 install -r freegpt/requirements.txt

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement mailgw_temporary_email (from versions: none)
ERROR: No matching distribution found for mailgw_temporary_email

![image](https://github.com/VadimBoev/freegpt-webui-v2/assets/3392684/3df726f9-9db0-4733-b3d1-694617f15c2b)

can it be in requirement.txt 

mailgw_temporary_email @ git+https://github.com/user/mailgw_temporary_email.git
Levenshtein>=0.23.0,<0.55.2

**Comment by VadimBoev** [comment]
The result of this error does not affect anything.

**Comment by nephaste** [comment]
it breaks the command... install -r requirements.txt, then other modules are not installed .. since pip install do not skip error

**Comment by VadimBoev** [comment]
I will review the list of packages later and compare them with g4f

**Comment by nephaste** [comment]
thanks 0.6 still have this issue i have to comment with # mailgw_temporary_email in requirements.txt to make script runs

ERROR: Could not find a version that satisfies the requirement mailgw_temporary_email (from versions: none)
ERROR: No matching distribution found for mailgw_temporary_email

not sure if it is really necessary module (i am using Python 3.11 branch)
