### ISSUE TITLE
payload and load time

### ISSUE THREAD

**Issue by Mylinde** [VadimBoev/freegpt-webui-v2#31]
Added flask-compress, minimized client sources, changed script loading order and stored some 3th party sources lokal to optimize performance. Would this https://github.com/xtekky/chatgpt-clone/pull/125 also be useful if it will be implemented?

**Comment by VadimBoev** [comment]
It's hard to say.

**Comment by Mylinde** [comment]
OK. So far switched to orjson, the other think affects only openai. So I think it is not so important.
