### ISSUE TITLE
可以添加docker的安装方式吗

### ISSUE THREAD

**Issue by mowang2024** [VadimBoev/freegpt-webui-v2#33]
请问可以添加docker的部署方式吗？

**Comment by mowang2024** [comment]
我不会这些操作，我想的是能在宝塔面板的docker中运行这个程序

**Comment by mowang2024** [comment]
非常感谢你为我解惑，但是我在centos7.9的服务器里安装了python3.11.2然后按照教程一步步来操作，但是最后都会报错说只能在虚拟环境运行，于是我弄了虚拟环境最后还是不行，不知道除了作者有没有搭建成功的例子

**Comment by mowang2024** [comment]
非常感谢你给我解答，然后我又重新试了一下最后成功搭建了，但是速度很慢，也有可能是我在中国大陆的原因，cdn.jsdelivr.net的css和js都无法加载

**Comment by mowang2024** [comment]
非常感谢你给我解答，然后我又重新试了一下最后成功搭建了，但是速度很慢，也有可能是我在中国大陆的原因，cdn.jsdelivr.net的css和js都无法加载

**Comment by mowang2024** [comment]
非常感谢你给我解答，然后我又重新试了一下最后成功搭建了，但是速度很慢，也有可能是我在中国大陆的原因，cdn.jsdelivr.net的css和js都无法加载

**Comment by mowang2024** [comment]
非常感谢，我已经将https://cdn.jsdelivr.net更改为可访问的域名，已经解决访问慢和无法访问的问题，再次感谢您为我解答。

**Comment by Mylinde** [comment]
If you like, check out my fork. 3th party sources excepted awesomefont are stored local. Also added flask-compress (reinstall necessary) or pip install flask-compress.
