### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PierrunoYT** [VadimBoev/freegpt-webui-v2#36]
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement mailgw_temporary_email (from versions: none)
ERROR: No matching distribution found for mailgw_temporary_email

C:\Users\pierr\freegpt-webui-v2>python3 run.py
Der Befehl "python3" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\pierr\freegpt-webui-v2>python  run.py
Traceback (most recent call last):
  File "C:\Users\pierr\freegpt-webui-v2\run.py", line 4, in <module>
    from server.website import Website
  File "C:\Users\pierr\freegpt-webui-v2\server\website.py", line 2, in <module>
    from flask_babel import refresh
ModuleNotFoundError: No module named 'flask_babel'

**Comment by VadimBoev** [comment]
Try please: https://github.com/VadimBoev/freegpt-webui-v2/releases/tag/v0.7
