### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by cloudseasail** [VadimBoev/freegpt-webui-v2#4]
GPT-3.5-turbo
Python 3.10.6
Linux Debian

`
{"_action":"_ask","error":"an error occurred HTTPSConnectionPool(host='sdk.vercel.ai', port=443): Max retries exceeded with url: /openai.jpeg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))","success":false}
`

**Comment by VadimBoev** [comment]
I have encountered such an error on one of the VDS. I didn't find an exact answer, try another version of python if possible
