### ISSUE TITLE
Exception in callback StreamRequest.release_curl()

### ISSUE THREAD

**Issue by merenguesL** [VadimBoev/freegpt-webui-v2#6]
windows
python3.11.6
![image](https://github.com/VadimBoev/freegpt-webui-v2/assets/69889206/50c6c79d-2b69-461f-a4f6-5958a09391af)

**Comment by VadimBoev** [comment]
I think it may be related to the encoding. What text are you trying to send?

**Comment by merenguesL** [comment]
![image](https://github.com/VadimBoev/freegpt-webui-v2/assets/69889206/7d9f644d-95d8-4447-8225-708a6cac8ab6)
i just said "hello" and it turned out to be an error after about 30s later...

**Comment by VadimBoev** [comment]
install another version of python, for example 3.10

**Comment by merenguesL** [comment]
sorry,but its still not working ,i got same errors

**Comment by VadimBoev** [comment]
I will update g4f next week, maybe it will help
